### ISSUE TITLE
StringIO and python3

### ISSUE THREAD

**Issue by azmeuk** [kxepal/viivakoodi#8]
Hi,
The examples in the README file contain a piece of code that is not valid in python3: `from StringIO import StringIO` while the library claims to python3 compatible. [python-future](http://python-future.org/compatible_idioms.html?highlight=stringio#stringio) advises to import StringIO from the `io` module instead. I could run the examples with replacing this line with `from io import BytesIO as StringIO`.

**Comment by lasley** [comment]
Thanks for the report @azmeuk - fixed up in #9!
